// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGY1HN8nTk31Wg6bkpsC00TVxca4RBPC4',
    appId: '1:646335881741:web:5cd71f94f8b0042807ab44',
    messagingSenderId: '646335881741',
    projectId: 'travelmate-2279f',
    authDomain: 'travelmate-2279f.firebaseapp.com',
    storageBucket: 'travelmate-2279f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAxI6MQm_F8edjU2VldIJ4Rmn-ybQEaw',
    appId: '1:646335881741:android:da39940a6e1694a507ab44',
    messagingSenderId: '646335881741',
    projectId: 'travelmate-2279f',
    storageBucket: 'travelmate-2279f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVy16cKl9BuVxQ0weNizdPSOLZCjCrW7A',
    appId: '1:646335881741:ios:bf0f5e123e9032e407ab44',
    messagingSenderId: '646335881741',
    projectId: 'travelmate-2279f',
    storageBucket: 'travelmate-2279f.appspot.com',
    iosBundleId: 'com.example.ttravelMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVy16cKl9BuVxQ0weNizdPSOLZCjCrW7A',
    appId: '1:646335881741:ios:bf0f5e123e9032e407ab44',
    messagingSenderId: '646335881741',
    projectId: 'travelmate-2279f',
    storageBucket: 'travelmate-2279f.appspot.com',
    iosBundleId: 'com.example.ttravelMate',
  );
}
